version: '2'
services:
   mysql:
      image: mysql:5.6
      environment:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: redhat
          MYSQL_RANDOM_ROOT_PASSWORD: redhat123
          MYSQL_DATABASE: mysqldb
      ports:
        - "3306:3306"
      volumes:
        - ./app:/var/lib/mysql
